defaults:
  - _self_
  # specify the network architecture
  - net: RIN
_target_: src.models.image_diffusion.ImageDiffusionLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: null

noise_scheduler:
  _target_: flow_matching.path.scheduler.CondOTScheduler

bregman_divergence:
  _target_: src.models.components.bregman_divergence.L2Loss


# specify objectives to optimize
objective: "velocity"

# compile model for faster training with pytorch 2.0
compile: false
