# @package _global_

defaults:
  - _self_
  - data: celeba # choose datamodule with `test_dataloader()` for evaluation
  - model: image_diffusion # choose model with `test_step()` for evaluation
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
